{
 "title": "Infinispan Monitor by Node",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "base_cpu_processCpuLoad" }
   ]
  },
  {
   "title": "Number of entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_container_stats_current_number_of_entries_in_memory"
    }
   ]
  },
  {
   "title": "Cache Access",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_statistics_hits"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_statistics_remove_hits"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_statistics_stores"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_memory_usedHeap_bytes" }
   ]
  },
  {
   "title": "Cache Miss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_statistics_misses"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_statistics_remove_misses"
    }
   ]
  },
  {
   "title": "Off Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_memory_usedNonHeap_bytes" }
   ]
  },
  {
   "title": "Evictions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_statistics_evictions"
    }
   ]
  }
 ]
}