{
 "title": "Infinispan Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Manage Cache ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_number_of_created_caches{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_number_of_running_caches{instance=\"192.168.1.1:11222\"}"
    }
   ]
  },
  {
   "title": "Cache Entry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_evictions{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_current_number_of_entries_in_memory{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_number_of_entries{instance=\"192.168.1.1:11222\"}"
    }
   ]
  },
  {
   "title": "Lock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_number_of_locks_available{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_number_of_locks_held{instance=\"192.168.1.1:11222\"}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cluster_size{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_required_minimum_number_of_nodes{instance=\"192.168.1.1:11222\"}"
    }
   ]
  },
  {
   "title": "Cache Access",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_hits{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_remove_hits{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_store_writes{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_stores{instance=\"192.168.1.1:11222\"}"
    }
   ]
  },
  {
   "title": "Cache Loader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_cache_loader_loads{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_cache_loader_misses{instance=\"192.168.1.1:11222\"}"
    }
   ]
  },
  {
   "title": "Repplication",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_rpc_manager_replication_count{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_rpc_manager_replication_failures{instance=\"192.168.1.1:11222\"}"
    }
   ]
  },
  {
   "title": "Cache miss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_misses{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_remove_misses{instance=\"192.168.1.1:11222\"}"
    }
   ]
  },
  {
   "title": "Memory Usage as Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_data_memory_used{instance=\"192.168.1.1:11222\"}"
    },
    {
     "expr": "vendor_cache_manager_default_cache_mycache_cluster_cache_stats_off_heap_memory_used{instance=\"192.168.1.1:11222\"}"
    }
   ]
  }
 ]
}